services:
  - type: web
    name: dns-detector-backend
    env: python
    rootDir: src/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

  - type: web
    name: dns-detector-frontend
    env: static
    rootDir: src/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: dns-detector-backend
          property: url
          append: /api
